
  CREATE TABLE METHODOLOGY_IDENTIFIERS
   (	METHODOLOGY_ID NUMBER NOT NULL ENABLE,
	IDENTIFIER_NAME VARCHAR2(30) NOT NULL ENABLE,
	VALUE VARCHAR2(100) NOT NULL ENABLE
   ) ;
  ALTER TABLE METHODOLOGY_IDENTIFIERS ADD CONSTRAINT PK_METHODOLOGY_IDENTIFIERS PRIMARY KEY (METHODOLOGY_ID, IDENTIFIER_NAME) ENABLE;
  ALTER TABLE METHODOLOGY_IDENTIFIERS ADD CONSTRAINT FK_MID_METHODOLOGIES FOREIGN KEY (METHODOLOGY_ID)
	  REFERENCES METHODOLOGIES (METHODOLOGY_ID) ON DELETE CASCADE ENABLE;

