
  CREATE TABLE PROJECT_DOCUMENT_TYPES_ML
   (	PROJECT_DOCUMENT_TYPE_ID NUMBER(22,0),
	PROJECT_DOCUMENT_TYPE_NAME VARCHAR2(100),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE PROJECT_DOCUMENT_TYPES_ML ADD CONSTRAINT PK_PROJECT_DOCUMENT_TYPES_ML PRIMARY KEY (PROJECT_DOCUMENT_TYPE_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE PROJECT_DOCUMENT_TYPES_ML ADD CONSTRAINT PROJECT_DOCUMENT_TYPES_ML_UK UNIQUE (PROJECT_DOCUMENT_TYPE_NAME, LANGUAGE_ID) ENABLE;
  ALTER TABLE PROJECT_DOCUMENT_TYPES_ML ADD CONSTRAINT FK_PROJECT_DOCUMENT_TYPES_ML_1 FOREIGN KEY (PROJECT_DOCUMENT_TYPE_ID)
	  REFERENCES PROJECT_DOCUMENT_TYPES (PROJECT_DOCUMENT_TYPE_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE PROJECT_DOCUMENT_TYPES_ML ADD CONSTRAINT FK_PROJECT_DOCUMENT_TYPES_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

