
  CREATE TABLE PROJECT_STAGES_ML
   (	PROJECT_STAGE_ID NUMBER(22,0),
	PROJECT_STAGE_NAME VARCHAR2(80),
	PROJECT_STAGE_DESCRIPTION VARCHAR2(2000),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE PROJECT_STAGES_ML ADD CONSTRAINT PK_PROJECT_STAGES_ML PRIMARY KEY (PROJECT_STAGE_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE PROJECT_STAGES_ML ADD CONSTRAINT PROJECT_STAGES_ML_UK UNIQUE (PROJECT_STAGE_NAME, LANGUAGE_ID) ENABLE;
  ALTER TABLE PROJECT_STAGES_ML ADD CONSTRAINT FK_PROJECT_STAGES_ML_1 FOREIGN KEY (PROJECT_STAGE_ID)
	  REFERENCES PROJECT_STAGES (PROJECT_STAGE_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE PROJECT_STAGES_ML ADD CONSTRAINT FK_PROJECT_STAGES_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

