alter TABLE PROJECT_REDUCTIONS add (
PERIOD_START DATE, 
PERIOD_END DATE,
PROJECT_MONITORED_VOLUME number,
PROJECT_DOCUMENT_ID number
) ;

ALTER TABLE PROJECT_REDUCTIONS add CONSTRAINT fk_pre_pdo_id foreign key(PROJECT_DOCUMENT_ID) 
    references project_documents(PROJECT_DOCUMENT_ID) enable;