
  CREATE TABLE PROJECT_CATEGORIES
   (	PROJECT_CATEGORY_ID NUMBER(38,0) NOT NULL ENABLE,
	NAME VARCHAR2(60) NOT NULL ENABLE,
	DESCRIPTION VARCHAR2(300)
   ) ;
  ALTER TABLE PROJECT_CATEGORIES ADD CONSTRAINT PK_PROJECT_CATEGORIES PRIMARY KEY (PROJECT_CATEGORY_ID) ENABLE;


  CREATE OR REPLACE TRIGGER trg_project_categories_biur
   BEFORE INSERT OR UPDATE ON project_categories
  FOR EACH ROW
BEGIN
  IF inserting THEN
    :NEW.project_category_id := project_categories_seq.NEXTVAL;
  END IF;
  NULL;
END trg_project_categories_biur;
/
ALTER TRIGGER trg_project_categories_biur ENABLE;

