
  CREATE TABLE PROJECTS_ML
   (	PROJECT_ID NUMBER(22,0),
	PROJECT_URL VARCHAR2(200),
	PROJECT_LOCATION VARCHAR2(400),
	PROJECT_CAPACITY_COMMENT VARCHAR2(1000),
	PROJECT_INVESTOR_COMMENT VARCHAR2(1000),
	PROJECT_INTERNAL_COMMENT VARCHAR2(2000),
	PROJECT_NAME VARCHAR2(500),
	PROJECT_SUMMARY VARCHAR2(2000),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE PROJECTS_ML ADD CONSTRAINT PK_PROJECTS_ML PRIMARY KEY (PROJECT_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE PROJECTS_ML ADD CONSTRAINT FK_PROJECTS_ML_1 FOREIGN KEY (PROJECT_ID)
	  REFERENCES PROJECTS (PROJECT_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE PROJECTS_ML ADD CONSTRAINT FK_PROJECTS_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

