
  CREATE TABLE PROJECT_TYPES_ML
   (	PROJECT_TYPE_ID NUMBER(22,0),
	PROJECT_TYPE_NAME VARCHAR2(40),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE PROJECT_TYPES_ML ADD CONSTRAINT PK_PROJECT_TYPES_ML PRIMARY KEY (PROJECT_TYPE_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE PROJECT_TYPES_ML ADD CONSTRAINT FK_PROJECT_TYPES_ML_1 FOREIGN KEY (PROJECT_TYPE_ID)
	  REFERENCES PROJECT_TYPES (PROJECT_TYPE_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE PROJECT_TYPES_ML ADD CONSTRAINT FK_PROJECT_TYPES_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

