
  CREATE TABLE PROJECT_DOCUMENT_STAGES
   (	PROJECT_DOCUMENT_STAGE_ID NUMBER NOT NULL,
	PROJECT_DOCUMENT_STAGE_NAME VARCHAR2(80) NOT NULL ENABLE,
	STAGE_DESCRIPTION VARCHAR2(2000) NOT NULL ENABLE
   ) ;
  ALTER TABLE PROJECT_DOCUMENT_STAGES ADD CONSTRAINT PK_PRJ_DOCUMENT_STAGES PRIMARY KEY (PROJECT_DOCUMENT_STAGE_ID) ENABLE;
  ALTER TABLE PROJECT_DOCUMENT_STAGES ADD CONSTRAINT UK_PRJ_DOCUMENT_STAGES_NAME UNIQUE (PROJECT_DOCUMENT_STAGE_NAME) ENABLE;

  CREATE OR REPLACE TRIGGER trg_PRJ_DOCUMENT_STAGES_biur
   BEFORE INSERT OR UPDATE ON PROJECT_DOCUMENT_STAGES
  FOR EACH ROW
BEGIN
  IF inserting THEN
    :NEW.PROJECT_DOCUMENT_STAGE_ID := PROJECT_DOCUMENT_STAGES_seq.NEXTVAL;
  END IF;
  NULL;
END trg_PRJ_DOCUMENT_STAGES_biur;
/
ALTER TRIGGER trg_PRJ_DOCUMENT_STAGES_biur ENABLE;

