
  CREATE TABLE PROJECT_DOCUMENT_HAS_STAGE
   (	ID NUMBER(38,0) NOT NULL ENABLE,
	PROJECT_DOCUMENT_ID NUMBER(38,0) NOT NULL ENABLE,
	PROJECT_DOCUMENT_STAGE_ID NUMBER(38,0) NOT NULL ENABLE,
	EFFECTIVE_DATE_FROM DATE NOT NULL ENABLE,
	EFFECTIVE_DATE_TO DATE,
	CREATE_BY VARCHAR2(30) NOT NULL ENABLE,
	CREATE_DATE DATE NOT NULL ENABLE,
	MODIFY_BY VARCHAR2(30) NOT NULL ENABLE,
	MODIFY_DATE DATE NOT NULL ENABLE
   ) ;
  ALTER TABLE PROJECT_DOCUMENT_HAS_STAGE ADD CONSTRAINT PK_PROJECT_DOCUMENT_HAS_STAGE PRIMARY KEY (ID) ENABLE;
  ALTER TABLE PROJECT_DOCUMENT_HAS_STAGE ADD CONSTRAINT FK_PDHS_PROJECTS FOREIGN KEY (PROJECT_DOCUMENT_ID)
	  REFERENCES PROJECT_DOCUMENTS (PROJECT_DOCUMENT_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE PROJECT_DOCUMENT_HAS_STAGE ADD CONSTRAINT FK_PDHS_PROJECT_STAGES FOREIGN KEY (PROJECT_DOCUMENT_STAGE_ID)
	  REFERENCES PROJECT_DOCUMENT_STAGES (PROJECT_DOCUMENT_STAGE_ID) ON DELETE CASCADE ENABLE;


  CREATE OR REPLACE TRIGGER trg_PDHS_biur
   BEFORE INSERT OR UPDATE ON PROJECT_DOCUMENT_HAS_STAGE
  FOR EACH ROW
BEGIN
  IF inserting THEN
    :NEW.id := PROJECT_DOCUMENT_HAS_STAGE_seq.NEXTVAL;
    :new.create_by := USER;
    :new.create_date := sysdate;
  END IF;
    :new.modify_by := USER;
    :new.modify_date := sysdate;
END trg_PDHS_biur;
/

ALTER TRIGGER trg_PDHS_biur ENABLE;

