
  CREATE TABLE REPRESENTATIVE_ROLES_ML
   (	REPRESENTATIVE_ROLE_ID NUMBER(22,0),
	REPRESENTATIVE_ROLE_NAME VARCHAR2(40),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE REPRESENTATIVE_ROLES_ML ADD CONSTRAINT PK_REPRESENTATIVE_ROLES_ML PRIMARY KEY (REPRESENTATIVE_ROLE_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE REPRESENTATIVE_ROLES_ML ADD CONSTRAINT REPRESENTATIVE_ROLES_ML_UK UNIQUE (REPRESENTATIVE_ROLE_NAME, LANGUAGE_ID) ENABLE;
  ALTER TABLE REPRESENTATIVE_ROLES_ML ADD CONSTRAINT FK_REPRESENTATIVE_ROLES_ML_1 FOREIGN KEY (REPRESENTATIVE_ROLE_ID)
	  REFERENCES REPRESENTATIVE_ROLES (REPRESENTATIVE_ROLE_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE REPRESENTATIVE_ROLES_ML ADD CONSTRAINT FK_REPRESENTATIVE_ROLES_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

