
  CREATE TABLE REPRESENTATIVES_ML
   (	REPRESENTATIVE_ID NUMBER(22,0),
	REPRESENTATIVE_NAME VARCHAR2(200),
	REPRESENTATIVE_TITLE VARCHAR2(100),
	REPRESENTATIVE_PHONE VARCHAR2(40),
	REPRESENTATIVE_EMAIL VARCHAR2(60),
	REPRESENTATIVE_NOTES VARCHAR2(2000),
	REPRESENTATIVE_ADDRESS VARCHAR2(300),
	REPRESENTATIVE_FAX VARCHAR2(80),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE REPRESENTATIVES_ML ADD CONSTRAINT PK_REPRESENTATIVES_ML PRIMARY KEY (REPRESENTATIVE_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE REPRESENTATIVES_ML ADD CONSTRAINT FK_REPRESENTATIVES_ML_1 FOREIGN KEY (REPRESENTATIVE_ID)
	  REFERENCES REPRESENTATIVES (REPRESENTATIVE_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE REPRESENTATIVES_ML ADD CONSTRAINT FK_REPRESENTATIVES_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

