
  CREATE TABLE STATES_ML
   (	STATE_ID CHAR(2),
	STATE_NAME VARCHAR2(60),
	STATE_CAPITAL VARCHAR2(60),
	LANGUAGE_ID NUMBER
   ) ;
  ALTER TABLE STATES_ML ADD CONSTRAINT PK_STATES_ML PRIMARY KEY (STATE_ID, LANGUAGE_ID) ENABLE;
  ALTER TABLE STATES_ML ADD CONSTRAINT STATES_ML_UK UNIQUE (STATE_NAME, LANGUAGE_ID) ENABLE;
  ALTER TABLE STATES_ML ADD CONSTRAINT FK_STATES_ML_1 FOREIGN KEY (STATE_ID)
	  REFERENCES STATES (STATE_ID) ON DELETE CASCADE ENABLE;
  ALTER TABLE STATES_ML ADD CONSTRAINT FK_STATES_ML_2 FOREIGN KEY (LANGUAGE_ID)
	  REFERENCES LANGUAGE (ID) ON DELETE CASCADE ENABLE;

